# Generated by Django 5.0.7 on 2024-08-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_like_is_liked_post_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='like',
            name='is_liked',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
