# Generated by Django 5.0.7 on 2024-08-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_like_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='label',
            field=models.CharField(choices=[('magonjwa', 'MAGONGWA'), ('chakula', 'CHAKULA'), ('others', 'OTHERS')], default='others', max_length=20),
        ),
    ]
