# Generated by Django 5.0.7 on 2024-08-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client/'),
        ),
    ]
