# Generated by Django 5.0.7 on 2024-08-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('paid', 'PAID'), ('Not', 'NOT PAID')], default='Not', max_length=20),
        ),
    ]
