# Generated by Django 5.0.7 on 2024-08-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matangazo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name_plural': 'Ads'},
        ),
    ]
