# Generated by Django 5.0.7 on 2025-03-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matangazo', '0002_alter_ads_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phamacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='dawa/')),
            ],
            options={
                'verbose_name_plural': 'Phamacy Image',
            },
        ),
    ]
