# Generated by Django 5.0.7 on 2025-03-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matangazo', '0003_phamacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='phamacy',
            name='promo_text',
            field=models.CharField(default='Available Soon', max_length=50),
        ),
    ]
