# Generated by Django 5.0.7 on 2024-09-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_reviewrating_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='price',
            field=models.IntegerField(default=5000),
        ),
    ]
