# Generated by Django 5.0.7 on 2025-03-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctorprofile_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
