# Generated by Django 5.0.7 on 2025-03-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctorprofile_is_online_doctorprofile_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('MB', 1), ('AC', 2), ('UIT', 3)], max_length=10, unique=True)),
                ('value', models.IntegerField(choices=[('MB', 1), ('AC', 2), ('UIT', 3)], editable=False)),
            ],
        ),
    ]
