# Generated by Django 5.0.7 on 2025-03-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_type',
            field=models.CharField(choices=[('MB', 'MB'), ('AC', 'AC'), ('UIT', 'UIT')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='value',
            field=models.IntegerField(choices=[('MB', 'MB'), ('AC', 'AC'), ('UIT', 'UIT')], editable=False),
        ),
    ]
