# Generated by Django 5.0.7 on 2025-03-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_level_level_type_alter_level_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='value',
            field=models.IntegerField(),
        ),
    ]
