# Generated by Django 5.0.7 on 2025-03-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_alter_level_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.level'),
        ),
    ]
