# Generated by Django 5.0.7 on 2025-03-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_doctorprofile_doctor_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='value',
            field=models.FloatField(),
        ),
    ]
